### ISSUE TITLE
StackBlitz link

### ISSUE THREAD

**Issue by Mkublbock** [rstropek-teaching/turmrechnen-quiz-4ahif-Mkublbock#1]
https://stackblitz.com/edit/mc-turmrechnen

**Comment by rstropek** [comment]
Nearly. Validation state is incorrect after initial load. Once values have been entered, everything works as expected.

Greetings,
Rainer Stropek.

**Comment by Mkublbock** [comment]
Thanks for the reply.

"Calculate-button" is now disabled on initial start.

Edit: By the way, do you have any further exercises on Angular because I'd like to do some more?

Greetings,
Matthias Küblböck

**Comment by rstropek** [comment]
Well done, extra point is secured.
